### ISSUE TITLE
Shorah is not correctly installed

### ISSUE THREAD

**Issue by XU-Nuo** [mingjiewang/qap#14]
When running `shorah`, the software can not find dependency `b2w`.

**Comment by XU-Nuo** [comment]
Solved by creating a virtual environment of python 3.9 and updated the installed Shorah to 1.99.2

**Comment by carolinasisco** [comment]
Hello, I have the same issue running EcnQSR, even when setting the program to ViQuaS, but could not solve it. I installed Shorah 1.99 but it keeps saying that shorah does not exist. Any advice on how to solve it?

**Comment by XU-Nuo** [comment]
> Hello, I have the same issue running EcnQSR, even when setting the program to ViQuaS, but could not solve it. I installed Shorah 1.99 but it keeps saying that shorah does not exist. Any advice on how to solve it?

Hi, are you using the docker image or trying to install QAP on your machine directly? If it's the first casem then the shorah 1.99 should be installed and invoked correctly, if it's the second case, make sure you install shorah in a different python virtual environment with all the dependent libraries installed, and invoke it in that environment. 

There are some conflicts among the libraries used in this project, especially in python, due to some history reasons.

**Comment by carolinasisco** [comment]
Hi, thank you for your answer. I´m not able to install it from docker since my ubuntu is 16.. I cannot update it since I´m working on a server (I don´t have sudo privilege). I installed qap on a virtual env with python 3.9. The problem I see is that when you run ./autoInstall it tries to install shorah from the lab webpage which is currently offline.. So I tried to modify it and installed shorah 1.99 myself using conda, but QAP still does not recognize it. I also tried to run EcnQSR with ViQuaS but the script keeps trying to check shorah´s existence and fails. Any other recommendation? Is there a way to avoid this shorah check up so It can continue with the script?

**Comment by XU-Nuo** [comment]
Hi, I am not responsible for project for quite a long time, but I am still willing to help. Basically, shorah is the key to the QSR process, so there is no way you can bypass it or the whole program just won't yield out the desired result. 

You can have a look at our dockerfile, and try to go through the installation of the dependencies on your own machine.
https://github.com/mingjiewang/qap/blob/a85dd49389cf7b6dd7fdc116a3b8f9dbef4f8fbc/Dockerfile#L76

To make it more clear about the python dependency: most of the implementation depends on python 2, while for and only for shorah, we used python 3, so basically you need to switch between python 2 and 3 based on the use case.

You can take a look at the implementation of how we switch between environments:
https://github.com/mingjiewang/qap/blob/2f1828101fed71241cc84dedfe310f85f29b0617/lib/QSR.pm#L54
